# Generated by Django 2.2.5 on 2019-11-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneDB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
