# Generated by Django 2.2.5 on 2019-11-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneDB', '0002_delete_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangerlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dangerlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
    ]
